map/urls.py
from django.urls import path
from . import views

app_name = 'map'

urlpatterns = [
    path('', views.index, name='index'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sightings/', include('sightings.urls')),
    path('map/', include('map.urls')),
]

sightings/urls.py
from django.urls import path
from . import views

app_name = 'sightings'

urlpatterns = [
    path('', views.index, name='index'),
    #path('map',views.map, name='map'),
    #path('sightings', views.sightings, name='index'),
    path('stats', views.stats, name='stats'),
    path('add', views.add, name='add'),
    path('<squirrel_ID>/', views.update, name='update'),

]

sightings/models.py
from django.db import models
from django.utils.translation import gettext as _


class Squirrel(models.Model):
    X = models.DecimalField(
	max_digits=100,
        decimal_places=15,
	help_text=_('X'),
)

    Y = models.DecimalField(
        max_digits=100,
        decimal_places=15,
        help_text=_('Y'),
)

    Unique_Squirrel_ID = models.CharField(
        max_length=29,
	help_text=_('Unique Squirrel ID'),
)
    
    AM = 'AM'
    PM = 'PM'
    Shift_choice = (
            (AM, 'AM'),
            (PM, 'PM'),
            )

    Shift = models.CharField(
        max_length=20,
        choices = Shift_choice,
        help_text=_('Shift'),
        default=AM,
        blank = True
)

    Date = models.CharField(
        max_length=100, 
        help_text=_('Date'),
        null = True,
        blank = True
)

    Juvenile='Juvenile'
    Adult='Adult'
    Age_choice = (
            (Juvenile,'Juvenile'),
            (Adult,'Adult'),
            (None,''),
            )

    Age = models.CharField(
        max_length=20,
        help_text=_('Age'),
        choices = Age_choice,
        default = Juvenile,
        blank=True,
)
    
    Black='Black'
    Cinnamon='Cinnamon'
    Gray='Gray'
    Color_choice = (
            (Black,'Black'),
            (Cinnamon,'Cinnamon'),
            (Gray,'Gray'),
            (None,''),
            )

    Primary_Fur_Color = models.CharField(
        max_length=15,
        help_text=_('Primary Fur Color'),
        choices = Color_choice,
        blank=True,
)

    Above_Ground='Above_Ground'
    Ground_Plane='Ground_Plane'
    Location_choice = (
            (Above_Ground,'Above_Ground'),
            (Ground_Plane,'Ground_Plane'),
            (None,''),
            )

    Location = models.CharField(
        max_length=100,
        help_text=_('Location'),
        choices = Location_choice,
        blank=True,
)

    Specific_Location = models.CharField(
        max_length=150,
        help_text=_('Specific Location'),
        blank=True,
)
    
    Running = models.BooleanField(
        default = False,
        help_text=_('Whether or not squirrel is running'),
)

    Chasing = models.BooleanField(
        default = False,
        help_text=_('Whether or not squirrel is chasing'),
)

    Climbing = models.BooleanField(
        default = False,
        help_text=_('Whether or not squirrel is climbing'),
)

    Eating = models.BooleanField(
        default = False,
        help_text=_('Whether or not squirrel is eating'),
)

    Foraging = models.BooleanField(
        default = False,
        help_text=_('Whether or not squirrel is foraging'),
)

    Other_Activities = models.CharField(
        max_length=150,
        help_text=_('Other Activities'),
        null=True,
        blank=True,
)

    Kuks = models.BooleanField(
        default = False,
        help_text=_('Whether or not squirrel is kuks'),
)

    Quaas = models.BooleanField(
        default = False,
        help_text=_('Whether or not squirrel is quaas'),
)

    Moans = models.BooleanField(
        default = False,
        help_text=_('Whether or not squirrel is moans'),
)

    Tail_flags = models.BooleanField(
        default = False,
        help_text=_('Whether or not squirrel is tail flags'),
)

    Tail_twitches = models.BooleanField(
        default = False,
        help_text=_('Whether or not squirrel is tail twitches'),
)

    Approaches = models.BooleanField(
        default = False,
        help_text=_('Whether or not squirrel is approaches'),
)

    Indifferent = models.BooleanField(
        default = False,
        help_text=_('Whether or not squirrel is indiferent'),
)

    Runs_from = models.BooleanField(
        default = False,
        help_text=_('Whether or not squirrel is runs from'),
)

    def __str__(self):
        return self.Unique_Squirrel_ID

# Create your models here.

sightings/forms.py
from django.forms import ModelForm

from .models import Squirrel

class SquirrelForm(ModelForm):
    class Meta:
        model = Squirrel
        fields = (
                'X',
                'Y',
                'Unique_Squirrel_ID',
                'Shift',
                'Date',
                'Age',
                'Primary_Fur_Color',
                'Location',
                'Specific_Location',
                'Running',
                'Chasing',
                'Climbing',
                'Eating',
                'Foraging',
                'Other_Activities',
                'Kuks',
                'Quaas',
                'Moans',
                'Tail_flags',
                'Tail_twitches',
                'Approaches',
                'Indifferent',
                'Runs_from',

        )

sightings/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.http import HttpResponse

from .models import Squirrel

from .forms import SquirrelForm

def index(request):
    squirrels = Squirrel.objects.all()
    context = {
            'squirrels': squirrels,
    }

    return render(request, 'sightings/index.html', context)

def stats(request):
    total = Squirrel.objects.all().count()
    adult_count = Squirrel.objects.filter(Age='Adult').count()
    primary_fur_color_count = Squirrel.objects.filter(Primary_Fur_Color='Cinnamon').count()
    location_count = Squirrel.objects.filter(Location='Ground Plane').count()
    running_count = Squirrel.objects.filter(Running='True').count()
    not_eating_count = Squirrel.objects.filter(Eating='False').count()
    context = {
            'total': total,
            'adult_count': adult_count,
            'primary_fur_color_count': primary_fur_color_count,
            'location_count': location_count,
            'running_count': running_count,
            'not_eating_count': not_eating_count,
    }

    return render(request, 'sightings/stats.html', context)

def add(request):
    if request.method == "POST":
        form = SquirrelForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('Your attemp to add a new sighting is Successful!')
        else:
            return JsonResponse({'errors': form.errors}, status=400)

    elif request.method == "GET":
        form = SquirrelForm()
        context = {
                'form': form,
        }
        
    return render(request, 'sightings/add.html', context) 

def update(request, squirrel_ID):
    obj = Squirrel.objects.filter(Unique_Squirrel_ID = squirrel_ID).first()

    if request.method == "POST":
        form = SquirrelForm(request.POST, instance = obj)
        if form.is_valid():
            form.save()
            return HttpResponse('Your attemp to update a new sighting is Successful!')
        else:
            return JsonResponse({'errors': form.errors}, status=400)

    elif request.method == "GET":
        form = SquirrelForm(instance = obj)
        context = {
                'form': form,
                'squirrel_ID': squirrel_ID,
        }

    return render(request, 'sightings/update.html', context)

# Create your views here.

sightings/templates/sightings/add.html
<!doctype html>

<html lang="en">
 	 <head>
   		<!-- Required meta tags -->
   		<meta charset="utf-8">
   		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"

   		<!-- Bootstrap CSS -->
   		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

   		<title>Add</title>
 	</head>

	<body
		<table align="center">
		<p>If you want to go back to the sightings without saving the form, click the button.</p>
		<form action=" {% url 'sightings:index' %} ">
			<button>Back to sightings</button>
		</form>
		</table>
		<br>
		<p align="left">Add a new sighting view here:</p>
		<p><form action="{% url 'sightings:add' %}" method="POST" name="add">
			{% csrf_token %}
			<table align="left">
				{{ form.as_table }}
				<br>
				<tr>
					<td></td>
					<td>     <input type="submit" name="Submit">     </td>
				</tr>
			</table>
		</form>
		</p>	
	</body>
</html>

sightings/templates/sightings/home.html
<!doctype html>

<html lang="en">
	<head>
		<meta charset=utf-8>
		<title>Home page</title>
	</head>
	
	<body>
		<h1 style="font-family:verdana;text-align:center">Squirrel Tracker</h1>
		<p>This is the home page for Squirrel Tracker. Feel free to click on the buttons below to see the details.</p>
		<br>
		<form action="/map/">
			<input type="submit" value="View the Map">
		</form><br>

		<form action="">
			<input type="submit" value="View Squirrel Sightings">
		</form><br>
	</body>
</html>

sightings/templates/sightings/index.html
<!doctype html>

<html lang="en">
 	 <head>
   		<!-- Required meta tags -->
   		<meta charset="utf-8">
   		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"

   		<!-- Bootstrap CSS -->
   		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

   		<title>Sightings</title>
 	</head>

	<body>
		<ul>
		<li>Add a new sighting view <a href="{% url 'sightings:add' %}">here</a>!</li>
		<li>Look at the general statistics <a href="{% url 'sightings:stats' %}">here</a>!</li>
		</ul>

		<table align="left">
			<tr>
				<th>    ID    </th>
				<th>    Date    </th>
				<th>    Sighting   </th>
			</tr>
				{% for squirrel in squirrels %}
			<tr>
				<td>  {{squirrel.Unique_Squirrel_ID}} <br> </td>
				<td>  {{squirrel.Date}} <br> </td>
				<td>  <a href="{% url 'sightings:update' squirrel.Unique_Squirrel_ID %}">Update a sighting</a> <br> </td>
			</tr>
				{% endfor %}
		</table>
	</body>
</html>

sightings/templates/sightings/stats.html
<!doctype html>

<html lang="en">
 	 <head>
   		<!-- Required meta tags -->
   		<meta charset="utf-8">
   		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"

   		<!-- Bootstrap CSS -->
   		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

   		<title>Update</title>
 	</head>
	<body align="center">
		<p>General statistics about the sightings: </p>

	<ul>
		<li>Total number of squiirels in the database: {{ total }}</li>
		<li>Total number of adult squirrels: {{ adult_count }} </li>
		<li>Total number of squirrels with primary color cinnamon: {{ primary_fur_color_count }} </li>
		<li>Total number of squirrels located on ground plane: {{ location_count }} </li>
		<li>Total number of squirrels that are running: {{ running_count }} </li>
		<li>Total number of squirrels that are not eating: {{ not_eating_count }} </li>
	</ul>
	<form action=" {% url 'sightings:index' %} ">
		<button align="center">Back to sightings</button>
	</form>
	</body>
</html>

sightings/templates/sightings/update.html
<!doctype html>

<html lang="en">
 	 <head>
   		<!-- Required meta tags -->
   		<meta charset="utf-8">
   		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"

   		<!-- Bootstrap CSS -->
   		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

   		<title>Update</title>
 	</head>
	<body>
		<p>If you want to go back to the sightings without saving the form, click the button.</p>
		<form action=" {% url 'sightings:index' %} ">
			<button>Back to sightings</button>
		</form>
		<br>

		<p align="left">Update a new sighting view here:</p>
		<form action="" method="POST" name="update">
			{% csrf_token %}
			<table align="left">

				The Squirrel ID you are updating right now is: {{squirrel_ID}}<br>

				{{ form.as_table }}
				<br>
				<tr>
					<td></td>
					<td>     <input type="submit" name="Submit">     </td>
				</tr>
			</table>
		</form>	
	</body>
</html>